// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package login

import (
	"sync"
)

var (
	lockManagerMockAuthenticate sync.RWMutex
)

// Ensure, that ManagerMock does implement Manager.
// If this is not the case, regenerate this file with moq.
var _ Manager = &ManagerMock{}

// ManagerMock is a mock implementation of Manager.
//
//     func TestSomethingThatUsesManager(t *testing.T) {
//
//         // make and configure a mocked Manager
//         mockedManager := &ManagerMock{
//             AuthenticateFunc: func(organization string) error {
// 	               panic("mock out the Authenticate method")
//             },
//         }
//
//         // use mockedManager in code that requires Manager
//         // and then make assertions.
//
//     }
type ManagerMock struct {
	// AuthenticateFunc mocks the Authenticate method.
	AuthenticateFunc func(organization string) error

	// calls tracks calls to the methods.
	calls struct {
		// Authenticate holds details about calls to the Authenticate method.
		Authenticate []struct {
			// Organization is the organization argument value.
			Organization string
		}
	}
}

// Authenticate calls AuthenticateFunc.
func (mock *ManagerMock) Authenticate(organization string) error {
	if mock.AuthenticateFunc == nil {
		panic("ManagerMock.AuthenticateFunc: method is nil but Manager.Authenticate was just called")
	}
	callInfo := struct {
		Organization string
	}{
		Organization: organization,
	}
	lockManagerMockAuthenticate.Lock()
	mock.calls.Authenticate = append(mock.calls.Authenticate, callInfo)
	lockManagerMockAuthenticate.Unlock()
	return mock.AuthenticateFunc(organization)
}

// AuthenticateCalls gets all the calls that were made to Authenticate.
// Check the length with:
//     len(mockedManager.AuthenticateCalls())
func (mock *ManagerMock) AuthenticateCalls() []struct {
	Organization string
} {
	var calls []struct {
		Organization string
	}
	lockManagerMockAuthenticate.RLock()
	calls = mock.calls.Authenticate
	lockManagerMockAuthenticate.RUnlock()
	return calls
}
